version: '3'
services:
  web:
    build: .
    ports:
      - "7000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - liverpool-db

  liverpool-db:
    container_name: orders_database
    image: postgres:16.3
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nano3110
      - POSTGRES_DB=liverdb